### ISSUE TITLE
Do not open function of withdrawing

### ISSUE THREAD

**Issue by carryon** [bitmax-exchange/api-doc#13]
Reference stolen case of Binance at 20190507 
https://www.chainnews.com/articles/203626954901.htm

**Comment by carryon** [comment]
That was the BEST course we should learn.
https://btc.com/e8b406091959700dbffcff30a60b190133721e5c39e89bb5fe23c5a554ab05ea

**Comment by yuez-gdm** [comment]
Thank you for the message. We don't have plan to open withdraw APIs in the near term.
